#Rename this file to config.toml if you want it to be used in sdig

[DNS_Servers]

[DNS_Servers.Mullvad] #you can repeat this pattern just like this
IP_List = ["194.242.2.2", "194.242.2.3"]
CN = "dns.mullvad.net"

[DNS_Servers.Cloudflare]
IP_List = ["1.1.1.1", "1.0.0.1"]
CN = "cloudflare-dns.com"

[DNS_Servers.Quad9]
IP_List = ["9.9.9.9", "149.112.112.112"]
CN = "dns.quad9.net"

#if you want to add a new server, just follow this format:
# first put [DNS_Servers.Server_Name]
#IP_List = ["", ""] #put both it's primary and secondary IPs, it's standard for DNS servers to have at least 2 IPs, if it doesn't just put the same IP twice
#then put CN="", this CN is for common name, it's what's needed to send requests to the server.
#You can use openssl to find it using the s_client command
#for example you can run openssl s_client -connect IP:853
#always use port 853 because that's the port that DNS over TLS operates on
#keep in mind if this server tries to downgrade, it will be dropped, we enforce TLS 1.3 and refuse to compromise on the privacy and safety of our users
#you can usually find the CN in the end certificate like this: subject=CN=dns.google
#keep in mind that there are other things called CN in the certificate so ensure it's the correct hostname of the DNS server
#it usually looks like a domain and will often contain the letters DNS in it.
#It can also often be found in the end of the original conection (the thing at the top)
